<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use OpenAI\Laravel\Facades\OpenAI;
use Smalot\PdfParser\Parser;
use Validator;

class PdfController extends Controller
{
    public function scan(Request $request){
        $file = $request->file('pdf');
        $parser = new Parser();
        $pdf = $parser->parseFile($file->getPathname());
        $content = $pdf->getText();
        $prompt = "Analyze the following text and determine the likelihood that it was generated by AI. 
        Return only a number from 0 to 100 representing the AI-written percentage. 
        Do not include any other words, symbols, or explanations.  
        Text: " . $content;

        $result = OpenAI::chat()->create([
            'model' => 'gpt-3.5-turbo',
            'messages' => [
                ['role' => 'user', 'content' => $prompt],
            ],
        ]);
        return response()->json(['data' => $result->choices[0]->message->content,'content' => $content]);

    }
}
